### ISSUE TITLE
About the step 9

### ISSUE THREAD

**Issue by Jrebort** [farabimahmud/sniper-simulator-7.2-pin-3.11-97998#1]
I can't understand the 9th step you wrote, can you write it in more detai？

**Comment by ahmadsb101** [comment]
Hi
Says that in the mentioned files just add `using namespace std;` after the` #include ` lines.

This Instruction is very well explained. Thanks to the contributor.

**Comment by farabimahmud** [comment]
Hopefully the aforementioned comment resolved the issues. Thank you.
